language: cpp
sudo: true
compiler: clang

branches:
  only:
    - master

env:
  - BAZEL_VERSION=0.10.1

before_install:
  - sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python
  - wget http://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel_$BAZEL_VERSION-linux-x86_64.deb
  - sudo dpkg -i bazel_$BAZEL_VERSION-linux-x86_64.deb

script:
  - bazel test simulate:simulation_service_test
