sudo: false  # Not needing sudo enables container builds.

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
      key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
    - bazel

script:
  - cd tests
  - bazel build :compdb
  - diff expected_file.json bazel-bin/compile_commands.json
